### ISSUE TITLE
If a friend puts on a hat, it renders for them, but not for me.

### ISSUE THREAD

**Issue by TaitoMagatsu91** [PinkGoosik/villager-hats#1]
Say I have the butcher hat. I put it on, and I can see it in my client. But my friend can't see it. They see me with my head armor only, or nothing if I've got no helmet on.

What's curious about this is that, if while wearing the hat I go to the nether and come back, my friend can then see it on me. It's so strange!

**Comment by PinkGoosik** [comment]
It seems to be an issue of trinkets mod or CCA https://github.com/emilyploszaj/trinkets/issues/113

**Comment by PinkGoosik** [comment]
Fixed on trinkets side
